CREATE DATABASE QuanLyChiTieuTietKiem
GO 


USE QuanLyChiTieuTietKiem
GO

CREATE TABLE NguoiDung
(
    Id INT PRIMARY KEY IDENTITY(1,1),
    TenDangNhap VARCHAR(100) NOT NULL UNIQUE,
    MatKhau VARCHAR(100) NOT NULL,
    TenHienThi NVARCHAR(100) NOT NULL,
    Avatar VARCHAR(100) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
);
GO

CREATE TABLE MucTieuTietKiem
(
    Id INT PRIMARY KEY IDENTITY(1,1),
    NguoiDung_Id INT REFERENCES NguoiDung(Id) ON DELETE CASCADE,
    TenMucTieu NVARCHAR(200) NOT NULL,
    MoTa NVARCHAR(200),
    SoTienCanTietKiem DECIMAL NOT NULL,
    SoTienDaTietKiemDuoc DECIMAL NOT NULL DEFAULT 0,
    NgayBD DATETIME NOT NULL,
    NgayKT DATETIME NOT NULL,
    TrangThai BIT DEFAULT 0,
    LoaiTietKiem NVARCHAR(50) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
);
GO

CREATE TABLE ChiTietTietKiem
(
     Id INT PRIMARY KEY IDENTITY(1,1),
     MucTieuTietKiem_Id INT REFERENCES MucTieuTietKiem(Id) ON DELETE CASCADE,
     TrangThai BIT DEFAULT 0,
     SoTien DECIMAL,
     Ngay DATETIME
);

CREATE TABLE QuanLyTienHienCo 
(
    Id INT PRIMARY KEY IDENTITY(1,1),
    NguoiDung_Id INT REFERENCES NguoiDung(Id) ON DELETE CASCADE,
    SoTienHienCo DECIMAL NOT NULL DEFAULT 0,
    SoTienDaSuDung DECIMAL NOT NULL DEFAULT 0,
    NgayBD DATETIME NOT NULL,
    NgayKT DATETIME NOT NULL,
    TrangThai BIT DEFAULT 0,
    CreatedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE ChiTietNguonThu
(
    Id INT PRIMARY KEY IDENTITY(1,1),
    QuanLyTienHienCo_Id INT REFERENCES QuanLyTienHienCo(Id) ON DELETE CASCADE,
    Nhom NVARCHAR(100) NOT NULL DEFAULT 'khác',
    SoTien DECIMAL NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
);
GO

CREATE TABLE ChiTieu
(
    Id INT PRIMARY KEY IDENTITY(1,1),
    QuanLyTienHienCo_Id INT REFERENCES QuanLyTienHienCo(id) ON DELETE CASCADE,
    TongChi DECIMAL NOT NULL,
    Ngay DATETIME NOT NULL DEFAULT GETDATE()
);
GO

CREATE TABLE ChiTietChiTieu 
(
    Id INT PRIMARY KEY IDENTITY(1,1),
    ChiTieu_Id INT REFERENCES ChiTieu(Id) ON DELETE CASCADE,
    Ten NVARCHAR(200) NOT NULL,
    Nhom NVARCHAR(100) NOT NULL DEFAULT 'khác',
    SoTien DECIMAL NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
);
GO